-  hosts: localhost
   vars_prompt:
   -    name: cont_name
        prompt: "Enter Container Name :"
        private: no
   tasks:
   -    name: "Repository"
        yum_repository:
          name: "Docker"
          description: "Docker Repo for RHEL8"
          baseurl: "https://download.docker.com/centos/linux/7/x86_64/stable"
          gpgcheck: "no"

   -    name: "creating docker package"
        package:
          name: "docker-ce-18.09.1-3.el7.x86_64"
          state: present

   -    name: "service starting"
        service:
          name: "docker"
          state: started
          enabled: yes 

   -    name: "Stopping SElinux"
        selinux:
          policy: targeted
          state: permissive 

   -    pip:
          name: docker

   -    name: "pull docker image"
        docker_image:
          name: "shashwatpp/sshcentos:14.2"
          source: pull  

   -    name: "launching docker container"
        docker_container: 
          name: "{{ cont_name }}"
          image: "shashwatpp/sshcentos:14.2"
          state:  started
          exposed_ports:
            - "80"
          ports:
            - "6678:80"

   -    name: "Retrieving IP of {{ cont_name }} container"
        docker_container_info:
           name: "{{ cont_name }}"
        register: info

   -    debug:
          var: info.container.NetworkSettings.IPAddress

   -    name: "Updating Ansible Inventory with docker IP"
        blockinfile:
          dest: "/root/ip.txt"
          block:  |
                        [docker]
                        {{ info[ 'container' ][ 'NetworkSettings' ][ 'IPAddress' ] }}   ansible_user=root   ansible_ssh_pass=root    ansible_connection=ssh
          marker: ""
 

           

